// Mocks generated by Mockito 5.4.4 from annotations
// in template_flutter_project/test/home/domin/home_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:template_flutter_project/future/home/models/general_response.dart'
    as _i5;
import 'package:template_flutter_project/future/home/models/user_model.dart'
    as _i6;

import 'home_repo_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeRepoTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepoTest extends _i1.Mock implements _i3.HomeRepoTest {
  MockHomeRepoTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<String, _i5.GeneralResponse<List<_i6.UserModel>>>>
      getUsers() => (super.noSuchMethod(
            Invocation.method(
              #getUsers,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<String,
                        _i5.GeneralResponse<List<_i6.UserModel>>>>.value(
                _FakeEither_0<String, _i5.GeneralResponse<List<_i6.UserModel>>>(
              this,
              Invocation.method(
                #getUsers,
                [],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<String, _i5.GeneralResponse<List<_i6.UserModel>>>>);
}
